data:
  #mongodb docker configuration
  mongodb.uri: mongodb://database:27017/easy_park
  mongo.repositories.enabled: true

api:
  weather:
    url: http://api.openweathermap.org/data/2.5/weather
    key: 130aab12fceacb0e3c68009f1e07b0ea

---
spring:
  profiles: dev
  data:
    mongodb.uri: mongodb://localhost:27017/easy_park

logging:
  level:
    org:
      springframework:
        web: DEBUG
api:
  weather:
    url: http://api.openweathermap.org/data/2.5/weather
    key: 130aab12fceacb0e3c68009f1e07b0ea

---
spring:
  profiles: prod
  data:
    mongodb:
      authentication-database: admin
      database: easy_park
      host: localhost
      password: <password>
      port: 27017
      username: <user>

api:
  weather:
    url: http://api.openweathermap.org/data/2.5/weather
    key: 130aab12fceacb0e3c68009f1e07b0ea

---
spring:
  profiles: test

api:
  weather:
    url: http://api.openweathermap.org/data/2.5/weather
    key: 130aab12fceacb0e3c68009f1e07b0ea